# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run ProxyCollector

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:

  run:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GithubApiToken: ${{ secrets.GITHUB_TOKEN }}
      GithubUser: ${{ github.repository_owner }}
      GithubRepo: ProxyCollector
      Timeout: 5000
      MaxThreadCount: 96
      SingboxPath: sing-box
      V2rayFormatResultPath: sub/proxies.txt
      SingboxFormatResultPath: sub/singbox.json
      Sources: |
https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/splitted/channels
https://raw.githubusercontent.com/ALIILAPRO/v2rayNG-Config/main/server.txt
https://raw.githubusercontent.com/Ashkan-m/v2ray/main/Sub.txt
https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/row-url/all.txt
https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/normal/mix
https://raw.githubusercontent.com/Kwinshadow/TelegramV2rayCollector/main/sublinks/mix.txt
https://raw.githubusercontent.com/Mohammadgb0078/IRV2ray/main/vless.txt
https://raw.githubusercontent.com/Mohammadgb0078/IRV2ray/main/vmess.txt
https://raw.githubusercontent.com/ts-sf/fly/main/v2
https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub
https://raw.githubusercontent.com/shabane/kamaji/master/hub/merged.txt
https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/sub/sub_merge.txt
https://raw.githubusercontent.com/iboxz/free-v2ray-collector/main/main/mix
https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/splitted/mixed
https://raw.githubusercontent.com/miladtahanian/V2RayCFGDumper/main/config.txt
https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/main/V2RAY_SUB.txt
https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/main/sub/mix
https://raw.githubusercontent.com/Vauth/node/main/Master
https://raw.githubusercontent.com/Vauth/node/main/Main
https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2
https://raw.githubusercontent.com/youfoundamin/V2rayCollector/main/mixed_iran.txt
https://raw.githubusercontent.com/youfoundamin/V2rayCollector/main/vmess_iran.txt
https://raw.githubusercontent.com/youfoundamin/V2rayCollector/main/vless_iran.txt
https://raw.githubusercontent.com/youfoundamin/V2rayCollector/main/trojan_iran.txt
https://raw.githubusercontent.com/Leon406/SubCrawler/main/sub/share/all4
https://raw.githubusercontent.com/Leon406/SubCrawler/main/sub/share/vless
https://raw.githubusercontent.com/itsyebekhe/HiN-VPN/main/subscription/normal/mix

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install sing-box
      run: |
        export VERSION="1.9.3"
        export SINGBOX="sing-box_${VERSION}_linux_amd64v3.deb"
        curl -fsSLO https://github.com/SagerNet/sing-box/releases/download/v${VERSION}/${SINGBOX}
        sudo dpkg -i $SINGBOX
        sudo apt-get install -f
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Run
      run: dotnet run --configuration Release --project ProxyCollector
